-- V1 — baseline: the schema as it was when Flyway was adopted (2026-09-28).
--
-- Taken from a schema-only dump of the working local database (which mirrors the manually
-- maintained production schema), so it matches the JPA entities under `entity/`.
--
--  * On a database that ALREADY has these tables, Flyway does NOT run this file: with
--    spring.flyway.baseline-on-migrate=true it records the existing schema as version 1
--    and only applies V2 and later. Compare a production schema dump with this file before
--    the first production deploy — Hibernate's ddl-auto=validate will refuse to start if
--    they differ.
--  * On an EMPTY database (fresh clone, CI, tests) this file creates the whole schema.
--
-- NEVER edit this file after it has been applied anywhere — add a new V<n>__<what>.sql.

-- ---------------------------------------------------------------------------
-- feedback
-- ---------------------------------------------------------------------------
CREATE TABLE public.feedback (
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message      character varying(2000) NOT NULL,
    owner_id     character varying(255)  NOT NULL,
    party_code   character varying(5)    NOT NULL,
    submitted_at timestamp(6) without time zone,
    CONSTRAINT feedback_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_feedback_owner_id     ON public.feedback USING btree (owner_id);
CREATE INDEX idx_feedback_submitted_at ON public.feedback USING btree (submitted_at);

-- ---------------------------------------------------------------------------
-- party_settings — one row per DJ (owner_id) / party (party_code)
-- ---------------------------------------------------------------------------
CREATE TABLE public.party_settings (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active                   boolean NOT NULL,
    active_provider          character varying(255),
    cooldown_minutes         integer NOT NULL,
    duplicate_check_window   integer NOT NULL,
    global_vibe              character varying(255),
    owner_id                 character varying(255) NOT NULL,
    party_code               character varying(5)   NOT NULL,
    playback_mode            character varying(255),
    request_limit            integer NOT NULL,
    spotify_access_token     character varying(2048),
    spotify_refresh_token    character varying(2048),
    spotify_token_expires_at timestamp(6) without time zone,
    fallback_playlist_url    character varying(500),
    fallback_shuffle         boolean DEFAULT true NOT NULL,
    CONSTRAINT party_settings_pkey PRIMARY KEY (id),
    CONSTRAINT ukat1ra56n8ttdykpqpypp8jnh4 UNIQUE (party_code),
    CONSTRAINT ukhimufx4ilbk1hjcpyfmk16wxa UNIQUE (owner_id),
    CONSTRAINT party_settings_active_provider_check CHECK (((active_provider)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'YOUTUBE'::character varying])::text[]))),
    CONSTRAINT party_settings_global_vibe_check CHECK (((global_vibe)::text = ANY ((ARRAY['ANY'::character varying, 'BACHATA_AND_KIZOMBA'::character varying, 'CLASSICAL_MUSIC'::character varying, 'CHILLOUT_AND_LOUNGE'::character varying, 'CLUB_AND_EDM'::character varying, 'DISCO_POLO'::character varying, 'HIP_HOP_AND_RAP'::character varying, 'JAZZ'::character varying, 'REGGAETON_AND_DANCEHALL'::character varying, 'POP_AND_DANCE'::character varying, 'RETRO_80S_90S'::character varying, 'ROCK_AND_METAL'::character varying, 'SALSA_AND_TIMBA'::character varying, 'WEDDING_CLASSICS'::character varying])::text[]))),
    CONSTRAINT party_settings_playback_mode_check CHECK (((playback_mode)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTO'::character varying])::text[])))
);

CREATE INDEX idx_owner_id ON public.party_settings USING btree (owner_id);

-- ---------------------------------------------------------------------------
-- song_requests
-- ---------------------------------------------------------------------------
CREATE TABLE public.song_requests (
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    decision     character varying(255),
    dj_comment   character varying(500),
    energy_level integer NOT NULL,
    party_code   character varying(5) NOT NULL,
    requested_at timestamp(6) without time zone,
    song_name    character varying(255),
    style        character varying(255),
    track_url    character varying(500),
    CONSTRAINT song_requests_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_party_code          ON public.song_requests USING btree (party_code);
CREATE INDEX idx_party_decision_time ON public.song_requests USING btree (party_code, decision, requested_at DESC);

-- ---------------------------------------------------------------------------
-- youtube_cache — search query -> video ID (permanent IDs, 30-day TTL in code)
-- ---------------------------------------------------------------------------
CREATE TABLE public.youtube_cache (
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   timestamp(6) without time zone NOT NULL,
    search_query character varying(500) NOT NULL,
    video_id     character varying(20)  NOT NULL,
    CONSTRAINT youtube_cache_pkey PRIMARY KEY (id),
    CONSTRAINT idx_youtube_cache_query UNIQUE (search_query)
);
