-- V21 — the DJ's devices that take notifications of new requests (Web Push): one row per browser that switched them on. The
-- endpoint is the push service's address of that browser (Google, Apple, Mozilla, Microsoft); p256dh and auth are its keys for the
-- message's encryption. A row goes when the DJ switches the notifications off there, when the push service says the address is
-- gone (404 / 410), or with the DJ's account.
CREATE TABLE public.push_subscription (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   character varying(255)  NOT NULL,
    endpoint   character varying(1000) NOT NULL,
    p256dh     character varying(200)  NOT NULL,
    auth       character varying(100)  NOT NULL,
    locale     character varying(20),
    created_at timestamptz             NOT NULL,
    CONSTRAINT push_subscription_pkey PRIMARY KEY (id),
    CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_subscription_owner_id ON public.push_subscription USING btree (owner_id);
