-- V2 — server-side fallback ("background music") tracks.
--
-- Phase 2 of the "Master Queue" roadmap (PROJECT_CONTEXT.md Section 14): when a DJ sets a fallback
-- playlist the backend fetches its video IDs ONCE (YouTube Data API playlistItems/videos, ~1 quota
-- unit per 50 tracks) and stores them here, instead of the browser iterating the playlist itself.
--
-- Rows are never deleted when the DJ changes the playlist: still-QUEUED tracks are flipped to
-- CANCELLED (soft invalidation), PLAYED rows stay as history. Only video IDs are stored (no titles),
-- and rows older than 30 days are purged — YouTube API data may not be kept longer (same rule as
-- youtube_cache).
CREATE TABLE public.fallback_track (
    id                bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    party_code        character varying(5)  NOT NULL,
    -- source of the track: a playlist ID (PL...) or 'V:<videoId>' for a single video
    playlist_id       character varying(64) NOT NULL,
    video_id          character varying(20) NOT NULL,
    -- order of the track within the source playlist, 0-based
    playlist_position integer NOT NULL,
    status            character varying(16) NOT NULL,
    fetched_at        timestamp(6) without time zone NOT NULL,
    played_at         timestamp(6) without time zone,
    CONSTRAINT fallback_track_pkey PRIMARY KEY (id),
    CONSTRAINT fallback_track_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'PLAYED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE INDEX idx_fallback_track_party_status ON public.fallback_track USING btree (party_code, status);
