-- V30 — the party's staff (a bartender, a second DJ): people who log in with their own Google account and work the owner's queue
-- and history — no settings. They join by the owner's invitation link (/join/{staff_token}); a new token makes the old link
-- dead, null = no link. member_name: the name of their Google account, for the owner's list of who has access. At most 10 per
-- party (the app's limit); a row goes when the owner takes the access away, with the member's account, or with the party.
ALTER TABLE public.party_settings ADD COLUMN staff_token varchar(32);
CREATE UNIQUE INDEX uk_party_settings_staff_token ON public.party_settings (staff_token);

CREATE TABLE public.party_staff (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    party_code  character varying(5)   NOT NULL,
    member_id   character varying(255) NOT NULL,
    member_name character varying(100),
    joined_at   timestamptz            NOT NULL,
    CONSTRAINT party_staff_pkey PRIMARY KEY (id),
    CONSTRAINT uk_party_staff_member UNIQUE (party_code, member_id),
    CONSTRAINT fk_party_staff_party FOREIGN KEY (party_code) REFERENCES public.party_settings (party_code) ON DELETE CASCADE
);

-- "which parties does this person work at" (the panel switcher, every request of a staff member checks it)
CREATE INDEX idx_party_staff_member_id ON public.party_staff USING btree (member_id);
