-- V34 — an invitation to a party's staff by the e-mail address of a Google account (the owner, 2026-10-10): the organiser types the
-- address and the role; the person sees the invitation when they log in with that account and joins ("Dołącz") or declines. No
-- e-mail is sent: the address is matched at the login (Google's verified `email`). A row goes when answered (a joined person is a
-- row of party_staff, without the address), cancelled, 30 days after it was made (StaffInvitationEntity.MAX_AGE_DAYS, the nightly
-- cleanup) or with the party. The staff and the invitations waiting count together to the party's 10.
--   email       — as the organiser typed it, in lower case: the organiser's list shows it
--   email_key   — the address the login is matched against (EmailAddresses.key: for Gmail without dots and "+…")
--   permissions — what the person will be able to do, as party_staff.permissions
CREATE TABLE public.staff_invitation (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    party_code  character varying(5)   NOT NULL,
    email       character varying(254) NOT NULL,
    email_key   character varying(254) NOT NULL,
    permissions character varying(200) NOT NULL,
    invited_at  timestamptz            NOT NULL,
    CONSTRAINT staff_invitation_pkey PRIMARY KEY (id),
    CONSTRAINT uk_staff_invitation_email UNIQUE (party_code, email_key),
    CONSTRAINT fk_staff_invitation_party FOREIGN KEY (party_code) REFERENCES public.party_settings (party_code) ON DELETE CASCADE
);

-- "is anyone inviting the person who just logged in" (every opening of the panel asks it)
CREATE INDEX idx_staff_invitation_email_key ON public.staff_invitation USING btree (email_key);
