-- V7 — a log of what the background playlist played.
--
-- The DJ history and the "previous track" button used to read the played tracks from fallback_track (status
-- PLAYED, played_at). But when the last queued track of a playlist is handed out, the next round starts and every
-- played track goes back in the queue with played_at cleared — so the playlist's history was at most one round long
-- and started over each time a short playlist looped (PROJECT_CONTEXT.md Section 5.4, "The history is one timeline").
--
-- fallback_play has one row per hand-out and is written in the same transaction as the hand-out, so it outlives the
-- rounds, the queue and a replaced playlist. Every row has its own id: the dashboard identifies a track in the
-- history as B:<id> (HistoryEntry.key), and a track that plays in two rounds is two entries with two keys.
--
-- video_id and title are a snapshot of what the YouTube API gave when the playlist was imported, so the row does
-- not depend on fallback_track any more. Both are YouTube API data (Non-Authorized Data, API Services Developer
-- Policies III.E.4.d: at most 30 calendar days), so fetched_at is copied from the track and the rows are purged by
-- it, in the same daily job as fallback_track — the log never holds API data longer than the table it came from.
CREATE TABLE public.fallback_play (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    party_code character varying(5)  NOT NULL,
    video_id   character varying(20) NOT NULL,
    -- NULL when the title was unknown (imported before V4, or the lookup of a single video failed)
    title      character varying(255),
    -- when the track was fetched from the YouTube API — basis of the 30-day retention
    fetched_at timestamp(6) without time zone NOT NULL,
    played_at  timestamp(6) without time zone NOT NULL,
    CONSTRAINT fallback_play_pkey PRIMARY KEY (id)
);

-- The history and "previous track" read one party's newest rows: WHERE party_code = ? ORDER BY played_at DESC, id DESC.
CREATE INDEX idx_fallback_play_party_played ON public.fallback_play USING btree (party_code, played_at DESC, id DESC);

-- Tracks that have been handed out before this migration: the ones still marked PLAYED in the current round. The
-- ones of an earlier round are gone (a new round cleared them) and cannot be recovered. Ordered, so that the ids
-- follow the play time.
INSERT INTO public.fallback_play (party_code, video_id, title, fetched_at, played_at)
SELECT party_code, video_id, title, fetched_at, played_at
FROM public.fallback_track
WHERE status = 'PLAYED' AND played_at IS NOT NULL
ORDER BY played_at, id;
